### ISSUE TITLE
Relayers with API on testnet

### ISSUE THREAD

**Issue by tech-somish** [0xProject/standard-relayer-api#17]
Hi, do you have any relayers working on testnet that offer API integration. Additionally, is there any direct API  to get  order details with order hash?

**Comment by fabioberger** [comment]
@tech-somish RadarRelay already has the standard relayer API implemented: https://radarrelay.com/standard-relayer-api and they have an endpoint specifically for retrieving an order's details by hash: https://radarrelay.com/standard-relayer-api#get-order-orderhash

**Comment by tech-somish** [comment]
Thanks @fabioberger. I do understand that but as far as I can understand RadarRelay is on main-net. Is there some relayer available on testnet with API integrations available?

**Comment by BMillman19** [comment]
@tech-somish try the aqueduct api: https://aqueduct.ercdex.com/#/rest

There are details under the "standard" section, you should be able to provide a testnet ID in order to request order information for that testnet

ex: curl https://api.ercdex.com/api/standard/1/v0/orders\?page\=1\&per_page\=20

This command will request orders from network 1, i.e. mainnet
