### ISSUE TITLE
Cannot GET /v2/token_pairs

### ISSUE THREAD

**Issue by thuongtin** [0xProject/standard-relayer-api#37]
This link is not working
https://api.radarrelay.com/v2/token_pairs?networkId=1

**Comment by WyseNynja** [comment]
The docs say the endpoint is /v2/asset_pairs: https://github.com/0xProject/standard-relayer-api/blob/master/http/v2.md#get-v2asset_pairs

However, that gives an error, too.

**Comment by WyseNynja** [comment]
Oh wait. radar relay has the SRA under /0x/

https://api.radarrelay.com/0x/v2/asset_pairs?networkId=1

**Comment by fragosti** [comment]
@thuongtin where did you find that link?

**Comment by michaelharrisonroth** [comment]
Hey everyone, sorry for the confusion on this. Due to the fact that we have both our Radar Relay API and implement the 0x SRA we decided to prefix with `0x`.

You can find the full API documentation for both the SRA and the Radar Relay API here:
https://developers.radarrelay.com/

SRA: https://developers.radarrelay.com/sra/v2
Radar: https://developers.radarrelay.com/feed-api/v2/
